# This is the GitHub Actions Workflow that builds the VocationNations API project
name: CI

# Define when to run the workflow
on: [push, pull_request]

# Define the collection of environment variables
env:
  GO111MODULE: on

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        go-version: [1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      # First, we install a distribution of Golang
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the tests of the project
      - name: Run tests
        run: go test -v ./...

      # Build the project to make sure an executable can be created
      - name: Run build
        run: go build -o vnations ./